// Generated by CoffeeScript 1.8.0
var Player, player, showNotification;

Player = (function() {
  Player.prototype.srcAudio = null;

  Player.prototype.audio = null;

  function Player(url) {
    this.saveStatus("stop");
    this.srcAudio = url;
    this.audio = new Audio;
    localStorage["volumeMute"] = "false";
    localStorage["volume"] = 100;
  }

  Player.prototype.play = function() {
    this.audio.src = this.srcAudio;
    this.audio.play();
    return this.saveStatus("play");
  };

  Player.prototype.stop = function() {
    this.audio.pause();
    return this.saveStatus("stop");
  };

  Player.prototype.command = function(c) {
    if (this[c] != null) {
      return this[c]();
    }
  };

  Player.prototype.saveStatus = function(val) {
    return localStorage["status"] = val;
  };

  Player.prototype.volumeMute = function() {
    return this.audio.muted = !this.audio.muted;
  };

  Player.prototype.setVolume = function() {
    return this.audio.volume = parseFloat(localStorage["volume"]) * 0.01;
  };

  return Player;

})();

player = new Player("http://maximum.fmtuner.ru/");

chrome.extension.onMessage.addListener(function(request) {
  return player.command(request.greeting);
});

showNotification = function() {
  var opt;
  opt = {
    type: "basic",
    title: "Primary Title",
    message: "Primary message to display",
    iconUrl: "logo.png"
  };
  return chrome.notifications.create("2", opt, function() {});
};
