// Generated by CoffeeScript 1.7.1
(function() {
  var Player, player, showNotification;

  Player = (function() {
    Player.prototype.srcAudio = null;

    Player.prototype.audio = null;

    function Player(url) {
      this.saveStatus("stop");
      this.srcAudio = url;
      this.audio = document.createElement("audio");
    }

    Player.prototype.play = function() {
      this.audio.src = this.srcAudio;
      this.audio.play();
      return this.saveStatus("play");
    };

    Player.prototype.stop = function() {
      this.audio.pause();
      return this.saveStatus("stop");
    };

    Player.prototype.command = function(c) {
      if (this[c] != null) {
        return this[c]();
      }
    };

    Player.prototype.saveStatus = function(val) {
      return localStorage["status"] = val;
    };

    return Player;

  })();

  player = new Player("http://maximum.fmtuner.ru/");

  chrome.extension.onMessage.addListener(function(request) {
    return player.command(request.greeting);
  });

  showNotification = function() {
    var opt;
    opt = {
      type: "basic",
      title: "Primary Title",
      message: "Primary message to display",
      iconUrl: "logo.png"
    };
    return chrome.notifications.create("2", opt, function() {});
  };

}).call(this);
