// Generated by CoffeeScript 1.8.0
var Track, track;

Track = (function() {
  Track.prototype.urlUpdate = "http://maximum.ru/getcurrenttrack.aspx?random=";

  Track.prototype.defaultTrackName = "MAXIMUM";

  Track.prototype.timeUpdate = 200000;

  function Track() {
    setInterval(((function(_this) {
      return function() {
        return _this.update();
      };
    })(this)), this.timeUpdate);
  }

  Track.prototype.update = function() {
    var urlUpdate, xhr;
    urlUpdate = this.urlUpdate + Math.random();
    xhr = new XMLHttpRequest;
    xhr.open("GET", urlUpdate, true);
    xhr.onload = (function(_this) {
      return function() {
        return _this.loadTrack(xhr.responseText.replace(/<\/?[^>]+>/g, ''));
      };
    })(this);
    return xhr.send();
  };

  Track.prototype.loadTrack = function(text) {
    if (text == null) {
      text = this.defaultTrackName;
    }
    console.log(text);
    localStorage.currentTrack = text;
    return window.dataBase.addItemHistory(text);
  };

  return Track;

})();

track = new Track;
