// Generated by CoffeeScript 1.8.0
var Options;

Options = (function() {
  function Options() {
    this.trackHistoryLoad();
  }

  Options.prototype.trackHistoryLoad = function() {
    return window.dataBase.getAll(function(data) {
      var date, i, table, tdDate, tdName, tr, _results;
      table = document.getElementById("tracks-history");
      _results = [];
      for (i in data) {
        tr = document.createElement("tr");
        tdDate = document.createElement("td");
        date = new Date(data[i].timestamp);
        tdDate.innerHTML = date.getDay() + '.' + date.getMonth() + '.' + date.getFullYear();
        tdName = document.createElement("td");
        tdName.innerHTML = data[i].name;
        tr.appendChild(tdDate);
        tr.appendChild(tdName);
        _results.push(table.appendChild(tr));
      }
      return _results;
    });
  };

  return Options;

})();

window.options = new Options();
